### ISSUE TITLE
Feature request - New destination Type : KAFKA

### ISSUE THREAD

**Issue by gitfirenz** [opendistro-for-elasticsearch/notifications#24]
# Goal

Enabling opendistro to notify alert with Kafka, (like Custom Webhook, Slack, SNS...)

# Settings

Type : KAFKA
Connection Settings : 
- TLS : PLAINTEXT/SSL
- Authentification : None/SASL_PLAINTEXT/SASL_SSL (at least)
- Username
- Password
- Bootstrap servers list
- Free kafka properties list (for sasl.mechanism or linger.ms by example)

Applicative Settings
- Kafka Topic
- Kafka Key (by default the Trigger name ?)
- Kafka Header : List of free key/value

**Comment by akbhatta** [comment]
This issue is been moved to https://github.com/opensearch-project/notifications/issues/6
